# Generated by Django 5.1.1 on 2024-10-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campName', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('contactno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='emergency_team_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('ContactNo', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='camp_coordinator_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
                ('contactNo', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='emergency_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('EMERGENCY_TEAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emergency_team_table')),
            ],
        ),
        migrations.CreateModel(
            name='Guidelines_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('CAMP_COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_coordinator_table')),
            ],
        ),
        migrations.AddField(
            model_name='emergency_team_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_table'),
        ),
        migrations.CreateModel(
            name='medical_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_table')),
            ],
        ),
        migrations.CreateModel(
            name='member_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('contactNo', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_coordinator_table')),
            ],
        ),
        migrations.CreateModel(
            name='asset_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('asset', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('MEMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member_table')),
            ],
        ),
        migrations.CreateModel(
            name='needs_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_coordinator_table')),
            ],
        ),
        migrations.CreateModel(
            name='public_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=200)),
                ('contactNo', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='goods_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public_table')),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
                ('contactNo', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp_coordinator_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='services_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer_table')),
            ],
        ),
    ]
