# Generated by Django 5.1.1 on 2024-11-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medical_request_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_request_table',
            name='CAMP',
        ),
        migrations.AddField(
            model_name='medical_request_table',
            name='VOLUNTEER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer_table'),
            preserve_default=False,
        ),
    ]
