# Generated by Django 5.1.1 on 2024-11-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_medical_request_table_camp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_request_table',
            name='EMERGENCY_TEAM',
        ),
        migrations.AddField(
            model_name='emergency_request_table',
            name='PUBLIC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.public_table'),
            preserve_default=False,
        ),
    ]
